In [6]:
# 1) Download cities.csv in C7W1 Activity folder

In [5]:
# 2) Import the CSV in a dataframe
import pandas as pd
df=pd.read_csv('cities.csv')
df

,LatD,"""LatM""","""LatS""","""NS""","""LonD""","""LonM""","""LonS""","""EW""","""City""","""State"""
0,41,5,59,"""N""",80,39,0,"""W""","""Youngstown""",OH
1,42,52,48,"""N""",97,23,23,"""W""","""Yankton""",SD
2,46,35,59,"""N""",120,30,36,"""W""","""Yakima""",WA
3,42,16,12,"""N""",71,48,0,"""W""","""Worcester""",MA
4,43,37,48,"""N""",89,46,11,"""W""","""Wisconsin Dells""",WI
...,...,...,...,...,...,...,...,...,...,...
123,39,31,12,"""N""",119,48,35,"""W""","""Reno""",NV
124,50,25,11,"""N""",104,39,0,"""W""","""Regina""",SA
125,40,10,48,"""N""",122,14,23,"""W""","""Red Bluff""",CA
126,40,19,48,"""N""",75,55,48,"""W""","""Reading""",PA
127,41,9,35,"""N""",81,14,23,"""W""","""Ravenna""",OH

In [9]:
# 3) Add a column to the dataframe
df['NewColumn']=None
df

,LatD,"""LatM""","""LatS""","""NS""","""LonD""","""LonM""","""LonS""","""EW""","""City""","""State""",NewColumn
0,41,5,59,"""N""",80,39,0,"""W""","""Youngstown""",OH,None
1,42,52,48,"""N""",97,23,23,"""W""","""Yankton""",SD,None
2,46,35,59,"""N""",120,30,36,"""W""","""Yakima""",WA,None
3,42,16,12,"""N""",71,48,0,"""W""","""Worcester""",MA,None
4,43,37,48,"""N""",89,46,11,"""W""","""Wisconsin Dells""",WI,None
...,...,...,...,...,...,...,...,...,...,...,...
123,39,31,12,"""N""",119,48,35,"""W""","""Reno""",NV,None
124,50,25,11,"""N""",104,39,0,"""W""","""Regina""",SA,None
125,40,10,48,"""N""",122,14,23,"""W""","""Red Bluff""",CA,None
126,40,19,48,"""N""",75,55,48,"""W""","""Reading""",PA,None
127,41,9,35,"""N""",81,14,23,"""W""","""Ravenna""",OH,None

In [10]:
# 4) Perform describe and info on dataframe
df.describe()

             LatD      "LatM"      "LatS"      "LonD"      "LonM"      "LonS"
count  128.000000  128.000000  128.000000  128.000000  128.000000  128.000000
mean    38.820312   30.765625   27.492188   93.250000   27.742188   26.960938
std      5.200596   16.426158   18.977814   15.466499   16.927937   18.727807
min     26.000000    1.000000    0.000000   71.000000    0.000000    0.000000
25%     35.000000   16.000000   11.000000   80.000000   14.000000   11.000000
50%     39.000000   31.000000   24.000000   89.500000   26.500000   23.500000
75%     42.250000   45.000000   47.000000  103.250000   40.250000   47.000000
max     50.000000   59.000000   59.000000  123.000000   58.000000   59.000000

In [11]:
# 5) Export and save this data as cities1.csv
df.to_csv('cities1.csv')

In [ ]:
# 1) Download CarSalesByModelStart.xlsx in C7W1 Activity folder

In [19]:
# 2) Import xlsx in a dataframe
df1=pd.read_excel('CarSalesByModelStart.xlsx')
df1

,Year,Month,Date,Model,Dealer ID,Quantity Sold,Profit
0,2018,January,2018-01-01 23:00:00,Beaufort,1222,10,15000.0
1,2018,January,2018-01-01 23:00:00,Salish,1222,13,39650.0
2,2018,January,2018-01-01 23:00:00,Labrador,1222,16,12800.0
3,2018,January,2018-01-01 23:00:00,Champlain,1222,3,6900.0
4,2018,January,2018-01-01 23:00:00,Hudson,1222,22,11000.0
...,...,...,...,...,...,...,...
1195,2019,December,2019-12-01 23:00:00,Beaufort,1288,12,18000.0
1196,2019,December,2019-12-01 23:00:00,Salish,1288,14,42700.0
1197,2019,December,2019-12-01 23:00:00,Labrador,1288,18,14400.0
1198,2019,December,2019-12-01 23:00:00,Champlain,1288,4,9200.0
1199,2019,December,2019-12-01 23:00:00,Hudson,1288,25,12500.0

In [20]:
# 3) Add a column to the dataframe
df1['NewColumn']=None
df1

,Year,Month,Date,Model,Dealer ID,Quantity Sold,Profit,NewColumn
0,2018,January,2018-01-01 23:00:00,Beaufort,1222,10,15000.0,None
1,2018,January,2018-01-01 23:00:00,Salish,1222,13,39650.0,None
2,2018,January,2018-01-01 23:00:00,Labrador,1222,16,12800.0,None
3,2018,January,2018-01-01 23:00:00,Champlain,1222,3,6900.0,None
4,2018,January,2018-01-01 23:00:00,Hudson,1222,22,11000.0,None
...,...,...,...,...,...,...,...,...
1195,2019,December,2019-12-01 23:00:00,Beaufort,1288,12,18000.0,None
1196,2019,December,2019-12-01 23:00:00,Salish,1288,14,42700.0,None
1197,2019,December,2019-12-01 23:00:00,Labrador,1288,18,14400.0,None
1198,2019,December,2019-12-01 23:00:00,Champlain,1288,4,9200.0,None
1199,2019,December,2019-12-01 23:00:00,Hudson,1288,25,12500.0,None

In [ ]:
# 4) Perform describe and info on dataframe
df1.describe()

,Year,Date,Dealer ID,Quantity Sold,Profit
count,1200.000000,1200,1200.000000,1200.00000,1200.000000
mean,2018.500000,2018-12-16 23:00:00,1281.800000,17.99750,24974.055208
min,2018.000000,2018-01-01 23:00:00,1212.000000,2.00000,4600.000000
25%,2018.000000,2018-06-24 11:00:00,1217.000000,11.00000,13500.000000
50%,2018.500000,2018-12-17 11:00:00,1256.000000,18.00000,18500.000000
75%,2019.000000,2019-06-09 11:00:00,1336.000000,24.00000,28922.812500
max,2019.000000,2019-12-01 23:00:00,1402.000000,48.00000,83875.000000
std,0.500208,NaN,72.453672,9.97432,17370.750612

In [22]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year           1200 non-null   int64
 1   Month          1200 non-null   object
 2   Date           1200 non-null   datetime64[ns]
 3   Model          1200 non-null   object
 4   Dealer ID      1200 non-null   int64
 5   Quantity Sold  1200 non-null   int64
 6   Profit         1200 non-null   float64
 7   NewColumn      0 non-null      object
dtypes: datetime64[ns](1), float64(1), int64(3), object(3)
memory usage: 75.1+ KB

In [16]:
# 5) Export and save this data as CarSalesByModelStart1.xlsx
df1.to_excel('CarSalesByModelStart1.xlsx')

In [ ]:
# 1) Download Jay.json in C7W1 Activity folder

In [17]:
# 2) Import the Json in dataframe
df2=pd.read_json('Jay.json')
df2

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [18]:
# 3) Add a column to the dataframe
df2['NewColumn']=None
df2

     Duration  Pulse  Maxpulse  Calories NewColumn
0          60    110       130     409.1      None
1          60    117       145     479.0      None
2          60    103       135     340.0      None
3          45    109       175     282.4      None
4          45    117       148     406.0      None
..        ...    ...       ...       ...       ...
164        60    105       140     290.8      None
165        60    110       145     300.4      None
166        60    115       145     310.2      None
167        75    120       150     320.4      None
168        75    125       150     330.4      None

[169 rows x 5 columns]

In [23]:
# 4) Perform describe and info on dataframe
df2.describe()

         Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.800000
std     42.299949   14.510259   16.450434   266.377134
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [24]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 169 entries, 0 to 168
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Duration   169 non-null    int64
 1   Pulse      169 non-null    int64
 2   Maxpulse   169 non-null    int64
 3   Calories   164 non-null    float64
 4   NewColumn  0 non-null      object
dtypes: float64(1), int64(3), object(1)
memory usage: 7.9+ KB

In [25]:
# 5) Export and save this data as Jay1.json
df2.to_json('Jay1.json')